include "../../studies/programs/eqv-design.pro";

control.runWhile='i<=900';
Solver.solver=params.simple_solver;
Input.input.file='studies/geometries/re-entrant.geo';
Input.input.onelab.Angle='5.25000000e+01';
Input.input.onelab.LengthRatio='3.33333333e-01';
Input.input.onelab.Thickness='5.50000000e-05';
// Input.input.file='studies/geometries/antichiral.geo';
// Input.input.onelab.Angle='0';
// Input.input.onelab.Elems=3.;
Input.input.verbose = true;
// Input.input.out_file="$(CASE_NAME).msh";
// Input.input.sampleWhen='(i-1)%100<1';
// Input.input.onelab.RepX='1';
// Input.input.onelab.RepY='1';
// Input.input.onelab.Rotation='180';
model.model.load.models='pbc';
model.model.load.pbc.model.H11="nan";
// model.model.load.pbc.model.H12=+50.;
// model.model.load.pbc.model.H21=+50.;
model.model.load.pbc.model.H22=-100.;
model.model.lattice.child.material.type = "ElasticRod";
model.model.lattice.child.material.side_length=[5.50000000e-05, 0.1];
Output+=params.lin_change;
Output.sampling.sampling.header='step,S_1111,S_1112,S_1121,S_1122,S_1211,S_1212,S_1221,S_1222,S_2111,S_2112,S_2121,S_2122,S_2211,S_2212,S_2221,S_2222';
Output.sampling.sampling.dataSets = ["i-1", "tangent.compliance[0]", "tangent.compliance[1]", "tangent.compliance[2]", "tangent.compliance[3]", "tangent.compliance[4]", "tangent.compliance[5]", "tangent.compliance[6]", "tangent.compliance[7]", "tangent.compliance[8]", "tangent.compliance[9]", "tangent.compliance[10]", "tangent.compliance[11]", "tangent.compliance[12]", "tangent.compliance[13]", "tangent.compliance[14]", "tangent.compliance[15]" ];
// Output.tangent.thickness=0.1;
// Output.tangent.solver.type="Nonlin";
// Output.tangent.solver.precision = 1e-9;
// Output.tangent.solver.maxIter = 100;
log.pattern = "*";
Output.modules+='paraview';

Output.sampling.sampling.file = "$(CASE_NAME)_explo.csv";
log.file                      = "$(CASE_NAME)_explo.log";
Output.paraview.output_format	= "$(CASE_NAME)/explo_%d";
