include "../../studies/programs/eqv-design.pro";

control.runWhile='i<=900';
Solver.solver=params.simple_solver;
Input.input.file='studies/geometries/re-entrant.geo';
Input.input.onelab.Angle='64.471220634490691369245999339962435963006843100907948288171106356';
Input.input.onelab.LengthRatio='0.75';
Input.input.onelab.Thickness='3.4506172839506174e-05';
// Input.input.file='studies/geometries/antichiral.geo';
// Input.input.onelab.Angle='0';
// Input.input.onelab.Elems=3.;
Input.input.verbose = true;
// Input.input.out_file="$(CASE_NAME).msh";
// Input.input.sampleWhen='(i-1)%100<1';
Input.input.onelab.RepX='1';
Input.input.onelab.RepY='1';
// Input.input.onelab.Rotation='180';
model.model.load.models='pbc';
model.model.load.pbc.model.H11="nan";
// model.model.load.pbc.model.H12=+50.;
// model.model.load.pbc.model.H21=+50.;
model.model.load.pbc.model.H22=-100.;
model.model.lattice.child.material.type = "ElasticRod";
model.model.lattice.child.material.side_length=[3.4506172839506174e-05, 0.1];
Output+=params.lin_change;
Output.sampling.sampling.header='            step,             E_x,             E_y,           nu_xy,           nu_yx,            G_xy,            G_yx';
// Output.sampling.sampling.dataSets = [ "tangentModuli.E_x", "tangentModuli.E_y", "tangentModuli.nu_xy", "tangentModuli.nu_yx","tangentModuli.dP_xy_xy", "tangentModuli.dP_yx_yx","tangentModuli.dP_yx_xy", "tangentModuli.dP_xy_yx"];
// Output.sampling.sampling.header='E_x,E_y,nu_xy,nu_yx,dP_xy_xy,dP_yx_yx,dP_yx_xy,dP_xy_yx';
// Output.tangent.thickness=0.1;
// Output.tangent.solver.type="Nonlin";
// Output.tangent.solver.precision = 1e-9;
// Output.tangent.solver.maxIter = 100;
log.pattern = "*";
Output.modules+='paraview';

Output.sampling.sampling.file = "$(CASE_NAME)_H22m.csv";
log.file                      = "$(CASE_NAME)_H22m.log";
Output.paraview.output_format	= "$(CASE_NAME)/H22m_%d";
